version: '3'
services:
    redis:
        image: redis:6
        container_name: "redis"
        volumes:
          - ./db_redis:/data
        ports:
            - 27017:27017
    web:
      container_name: "reguinback"
      build: django/.
      restart: always
      #command:  python manage.py runserver 0.0.0.0:8000
      volumes:
        - ${PWD}/app:/app
        - /sys/class/gpio:/sys/class/gpio
      devices:
        - /dev/gpiomem:/dev/gpiomem
        - /dev/mem:/dev/mem
      privileged: true
      ports:
        - "8000:8000"
      depends_on:
        - redis
    telebot:
      build:
        context: ./telebot
      container_name: telebot
      volumes: 
        - ./bot:/bot/app
      env_file:
        - .env

